spring.application.name=portfolio-backend-ia

# OpenRouter (Con valores por defecto tras los dos puntos)
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=${OPENROUTER_BASE_URL}
spring.ai.openai.chat.options.model=${OPENROUTER_MODEL}

# Deshabilitar Embeddings de OpenAI (usamos Transformers local)
spring.ai.openai.embedding.enabled=false

# Servidor
server.port=8080

# Logging
logging.level.tech.matiaszelarayan=DEBUG
logging.level.org.springframework.ai=INFO

# Configuración de CORS
cors.allowed-origins=http://localhost:4321,https://matiaszelarayan.tech

# Seguridad
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never